version: 2.1
orbs:
  codecov: codecov/codecov@1.1.3
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-
      - run:
          name: Compile
          command: sbt compile
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}
      - run:
          name: Lint
          command: sbt +scalafmtCheck +scalafmtCheckAll
      - run:
          name: Dependency Check
          command: sbt +dependencyUpdates
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: Test
          command: sbt +coverage +test
      - run:
          name: Coverage
          command: sbt +coverageReport +coverageAggregate
      - store_test_results:
          path: test-results
      - codecov/upload:
          file: target/*/coverage-report/cobertura.xml
  publish:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: GPG Setup
          command: ./bin/gpg-setup.sh
      - run:
          name: Import PGP key
          command: echo -e $PGP_SECRET | base64 --decode | gpg --import --no-tty --batch --yes
      - run:
          name: Publish
          command: cat /dev/null | sbt +publishSigned

workflows:
  version: 2
  cicd:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - publish:
          context:
            - sonatype
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
